import type { Source } from "./schema";

/**
 * Registro central de fuentes.
 *
 * Regla del proyecto: no se inventan citas ni bibliografía. Cada entrada de
 * este archivo corresponde a una obra, norma o serie estadística que existe y
 * que puede verificarse. Cuando una fuente respalda sólo una parte de lo que
 * afirma un artículo, eso se aclara en `note`.
 *
 * Las series estadísticas se registran como fuente (el organismo y su serie),
 * no como número. Los números viven en bloques `figure`, que exigen fecha.
 */
export const SOURCES: Source[] = [
  // --- Fuentes primarias: normas argentinas ---
  {
    id: "cn-argentina",
    kind: "primaria",
    title: "Constitución de la Nación Argentina",
    year: "1853, con reformas de 1860, 1866, 1898, 1957 y 1994",
    publisher: "República Argentina",
    url: "https://www.argentina.gob.ar/normativa/nacional/ley-24430-804/texto",
    note: "Texto oficial vigente publicado en el sistema de información normativa del Estado nacional (Ley 24.430).",
  },
  {
    id: "ley-23928",
    kind: "primaria",
    title: "Ley 23.928 de Convertibilidad del Austral",
    year: "1991",
    publisher: "Congreso de la Nación Argentina",
    url: "https://www.argentina.gob.ar/normativa/nacional/ley-23928-328",
    note: "Norma que estableció la paridad fija y la obligación de respaldo en reservas.",
  },
  {
    id: "ley-25561",
    kind: "primaria",
    title: "Ley 25.561 de Emergencia Pública y Reforma del Régimen Cambiario",
    year: "2002",
    publisher: "Congreso de la Nación Argentina",
    url: "https://www.argentina.gob.ar/normativa/nacional/ley-25561-71477",
    note: "Norma que puso fin a la convertibilidad.",
  },
  {
    id: "carta-organica-bcra",
    kind: "primaria",
    title: "Carta Orgánica del Banco Central de la República Argentina (Ley 24.144 y modificatorias)",
    year: "1992",
    publisher: "Congreso de la Nación Argentina",
    url: "https://www.bcra.gob.ar/Institucional/Carta_Organica.asp",
    note: "Define el mandato, las funciones y los límites del BCRA, incluidos los adelantos transitorios al Tesoro.",
  },
  {
    id: "ley-saenz-pena",
    kind: "primaria",
    title: "Ley 8.871, conocida como Ley Sáenz Peña",
    year: "1912",
    publisher: "Congreso de la Nación Argentina",
    note: "Estableció el sufragio universal masculino, secreto y obligatorio para nativos y naturalizados.",
  },

  // --- Fuentes primarias: obras de autores ---
  {
    id: "alberdi-bases",
    kind: "primaria",
    title:
      "Bases y puntos de partida para la organización política de la República Argentina",
    author: "Juan Bautista Alberdi",
    year: "1852",
    note: "Obra que influyó directamente sobre el texto constitucional de 1853. La segunda edición incluye un proyecto de constitución.",
  },
  {
    id: "alberdi-sistema",
    kind: "primaria",
    title: "Sistema económico y rentístico de la Confederación Argentina según su Constitución de 1853",
    author: "Juan Bautista Alberdi",
    year: "1854",
    note: "Desarrollo económico del programa constitucional: producción, distribución y rentas públicas.",
  },
  {
    id: "smith-wn",
    kind: "libro",
    title: "An Inquiry into the Nature and Causes of the Wealth of Nations",
    author: "Adam Smith",
    year: "1776",
    note: "Suele citarse por libro y capítulo (por ejemplo I.ii) porque la paginación varía entre ediciones.",
  },
  {
    id: "smith-tms",
    kind: "libro",
    title: "The Theory of Moral Sentiments",
    author: "Adam Smith",
    year: "1759",
  },
  {
    id: "locke-two-treatises",
    kind: "libro",
    title: "Two Treatises of Government",
    author: "John Locke",
    year: "1689",
    note: "El Segundo Tratado contiene la teoría del estado de naturaleza, la propiedad y el gobierno limitado.",
  },
  {
    id: "mill-on-liberty",
    kind: "libro",
    title: "On Liberty",
    author: "John Stuart Mill",
    year: "1859",
  },
  {
    id: "bastiat-ley",
    kind: "libro",
    title: "La Ley",
    author: "Frédéric Bastiat",
    year: "1850",
  },
  {
    id: "bastiat-ve",
    kind: "libro",
    title: "Lo que se ve y lo que no se ve",
    author: "Frédéric Bastiat",
    year: "1850",
    note: "Origen de la parábola de la ventana rota y del análisis de costos no visibles.",
  },
  {
    id: "tocqueville-democracia",
    kind: "libro",
    title: "La democracia en América",
    author: "Alexis de Tocqueville",
    year: "1835 y 1840",
  },
  {
    id: "hayek-camino",
    kind: "libro",
    title: "Camino de servidumbre",
    author: "Friedrich A. Hayek",
    year: "1944",
  },
  {
    id: "hayek-constitution",
    kind: "libro",
    title: "Los fundamentos de la libertad",
    author: "Friedrich A. Hayek",
    year: "1960",
  },
  {
    id: "hayek-knowledge",
    kind: "academica",
    title: "The Use of Knowledge in Society",
    author: "Friedrich A. Hayek",
    year: "1945",
    publisher: "The American Economic Review, vol. 35, n.º 4",
    note: "Artículo donde plantea que el conocimiento económico está disperso y que los precios lo transmiten.",
  },
  {
    id: "mises-accion",
    kind: "libro",
    title: "La acción humana",
    author: "Ludwig von Mises",
    year: "1949",
  },
  {
    id: "mises-socialismo",
    kind: "libro",
    title: "El socialismo",
    author: "Ludwig von Mises",
    year: "1922",
    note: "Contiene el argumento del cálculo económico bajo socialismo, publicado antes como artículo en 1920.",
  },
  {
    id: "friedman-capitalismo",
    kind: "libro",
    title: "Capitalismo y libertad",
    author: "Milton Friedman",
    year: "1962",
  },
  {
    id: "friedman-elegir",
    kind: "libro",
    title: "Libertad de elegir",
    author: "Milton Friedman y Rose Friedman",
    year: "1980",
  },
  {
    id: "friedman-counter",
    kind: "academica",
    title: "The Counter-Revolution in Monetary Theory",
    author: "Milton Friedman",
    year: "1970",
    publisher: "Institute of Economic Affairs, Occasional Paper 33",
    note: "Texto donde aparece la formulación de que la inflación es siempre y en todo lugar un fenómeno monetario.",
  },
  {
    id: "friedman-schwartz",
    kind: "libro",
    title: "A Monetary History of the United States, 1867–1960",
    author: "Milton Friedman y Anna J. Schwartz",
    year: "1963",
  },
  {
    id: "nozick-anarquia",
    kind: "libro",
    title: "Anarquía, Estado y utopía",
    author: "Robert Nozick",
    year: "1974",
  },
  {
    id: "rothbard-nueva-libertad",
    kind: "libro",
    title: "Hacia una nueva libertad: el manifiesto libertario",
    author: "Murray N. Rothbard",
    year: "1973",
  },
  {
    id: "rothbard-etica",
    kind: "libro",
    title: "La ética de la libertad",
    author: "Murray N. Rothbard",
    year: "1982",
  },
  {
    id: "rawls-justicia",
    kind: "libro",
    title: "Teoría de la justicia",
    author: "John Rawls",
    year: "1971",
    note: "No es una obra liberal en el sentido de este sitio, pero es el principal interlocutor crítico del liberalismo clásico contemporáneo.",
  },
  {
    id: "hazlitt-leccion",
    kind: "libro",
    title: "La economía en una lección",
    author: "Henry Hazlitt",
    year: "1946",
  },
  {
    id: "hume-tratado",
    kind: "libro",
    title: "Tratado de la naturaleza humana",
    author: "David Hume",
    year: "1739–1740",
  },
  {
    id: "sarmiento-facundo",
    kind: "libro",
    title: "Facundo. Civilización y barbarie",
    author: "Domingo F. Sarmiento",
    year: "1845",
  },
  {
    id: "acemoglu-robinson",
    kind: "libro",
    title: "Por qué fracasan los países",
    author: "Daron Acemoglu y James A. Robinson",
    year: "2012",
    note: "Defiende que las instituciones inclusivas explican las diferencias de desarrollo. Es una tesis discutida, no un consenso cerrado.",
  },
  {
    id: "ostrom-commons",
    kind: "libro",
    title: "El gobierno de los bienes comunes",
    author: "Elinor Ostrom",
    year: "1990",
    note: "Documenta arreglos comunitarios de gestión de recursos que no son ni Estado ni propiedad privada individual.",
  },
  {
    id: "coase-social-cost",
    kind: "academica",
    title: "The Problem of Social Cost",
    author: "Ronald Coase",
    year: "1960",
    publisher: "The Journal of Law and Economics, vol. 3",
  },
  {
    id: "sen-desarrollo",
    kind: "libro",
    title: "Desarrollo y libertad",
    author: "Amartya Sen",
    year: "1999",
    note: "Amplía la idea de libertad más allá de la no interferencia. Útil como crítica interna al liberalismo clásico.",
  },

  // --- Organismos y estadísticas oficiales ---
  {
    id: "indec",
    kind: "oficial",
    title: "Instituto Nacional de Estadística y Censos (INDEC)",
    publisher: "República Argentina",
    url: "https://www.indec.gob.ar/",
    note: "Organismo oficial de estadística. Produce el IPC, la EPH (pobreza, empleo), el PIB y el comercio exterior.",
  },
  {
    id: "indec-ipc",
    kind: "oficial",
    title: "Índice de Precios al Consumidor (IPC), serie histórica",
    publisher: "INDEC",
    url: "https://www.indec.gob.ar/indec/web/Nivel4-Tema-3-5-31",
    note: "La serie tiene cortes metodológicos y un período (2007–2015) cuestionado. Ver el artículo sobre estadísticas públicas.",
  },
  {
    id: "bcra",
    kind: "oficial",
    title: "Banco Central de la República Argentina — estadísticas monetarias y cambiarias",
    publisher: "BCRA",
    url: "https://www.bcra.gob.ar/PublicacionesEstadisticas/Principales_variables.asp",
    note: "Base monetaria, reservas, tipo de cambio, tasas y pasivos remunerados.",
  },
  {
    id: "minecon",
    kind: "oficial",
    title: "Ministerio de Economía — Informe mensual de ingresos y gastos del Sector Público Nacional",
    publisher: "República Argentina",
    url: "https://www.argentina.gob.ar/economia/sechacienda/informessectorpublico",
    note: "Fuente primaria para resultado fiscal primario y financiero.",
  },
  {
    id: "presupuesto-abierto",
    kind: "oficial",
    title: "Presupuesto Abierto",
    publisher: "Ministerio de Economía, República Argentina",
    url: "https://www.presupuestoabierto.gob.ar/",
    note: "Permite ver el gasto público nacional por finalidad, función y jurisdicción.",
  },
  {
    id: "afip-arca",
    kind: "oficial",
    title: "Estadísticas de recaudación tributaria",
    publisher: "Agencia de Recaudación y Control Aduanero (ex AFIP)",
    url: "https://www.afip.gob.ar/estudios/",
    note: "Serie oficial de recaudación por impuesto.",
  },
  {
    id: "fmi-weo",
    kind: "organismo",
    title: "World Economic Outlook Database",
    publisher: "Fondo Monetario Internacional",
    url: "https://www.imf.org/en/Publications/WEO",
    note: "Útil para comparaciones internacionales. Para datos argentinos conviene preferir la fuente nacional.",
  },
  {
    id: "banco-mundial",
    kind: "organismo",
    title: "World Development Indicators",
    publisher: "Banco Mundial",
    url: "https://databank.worldbank.org/source/world-development-indicators",
  },
  {
    id: "ocde-revenue",
    kind: "organismo",
    title: "Estadísticas tributarias en América Latina y el Caribe",
    publisher: "OCDE / CEPAL / BID / CIAT",
    url: "https://www.oecd.org/tax/tax-policy/revenue-statistics-latin-america-and-caribbean.htm",
    note: "Permite comparar presión tributaria entre países con metodología homogénea.",
  },
  {
    id: "fmi-censura-2013",
    kind: "organismo",
    title: "Declaración del Directorio Ejecutivo del FMI sobre las estadísticas de Argentina",
    publisher: "Fondo Monetario Internacional",
    year: "2013",
    url: "https://www.imf.org/en/News/Articles/2015/09/14/01/49/pr1333",
    note: "Declaración de censura por la calidad de los datos oficiales de IPC y PIB.",
  },
];

export const SOURCES_BY_ID: Record<string, Source> = Object.fromEntries(
  SOURCES.map((s) => [s.id, s]),
);

export function getSource(id: string): Source | undefined {
  return SOURCES_BY_ID[id];
}
